// import "./1basic";
// import "./2weakMap";
// import "./3changedeps";
// import "./4nestedEffects";
// import "./5overflow";
// import "./6scheduler";
// import "./7lazy";
// import "./8computed";
import "./9computed-cache";
// import "./10computed-react";
